# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # setup nobita machine
  config.vm.define "nobita" do |node|
    node.vm.box = "centos/7"
    node.vm.hostname = "nobita"
    node.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1500"]
      vb.customize ["modifyvm", :id, "--cpus", "2"]
    end
    node.vm.network "private_network", ip: "192.168.20.10"
  end
  
  end